Issue #22759: Prevent CLI from adding invalid routed interfaces (#3901)
What I did
Currently, config interface ip add will accept EthernetX interfaces which do not have an underlying port or portchannel associated with them. This violates the yang model, so if these entries are added to ConfigDB, 'config replace' and 'config reload' don't work properly. To make matters worse, the implementation of config interface ip remove does not detect these invalid entries, so once they are added they cannot be removed through the CLI. I modified the command to reject invalid cases.

Fixes: #22759

How I did it
Add a check for this case into the config interface ip add CLI command to avoid invalid cases of this form by checking to ensure that the interface which is passed is associated with a valid port or port channel if it is an Ethernet or PortChannel interface. There is already an existing check for vlan interfaces.

How to verify it
Modify existing test cases to handle expected behavior, verify that they all pass.

Previous command output (if the output of a command-line utility has changed)
admin@gold113-dut:~$ sudo config interface ip add EthernetNR 1.2.3.4
admin@gold113-dut:~$ sudo config interface ip add EthernetJustMadeUp 1.2.3.4
admin@gold113-dut:~$ sudo config interface ip add Ethernet99999999 1.2.3.4
admin@gold113-dut:~$ sudo config interface ip add Ethernet-totally-not-real 1.2.3.4
admin@gold113-dut:~$ sudo config interface ip remove EthernetNR 1.2.3.4
Cannot find device "EthernetNR"
admin@gold113-dut:~$ sudo config replace -d /etc/sonic/config_db.json
** DRY RUN EXECUTION **
Config Replacer: Config replacement starting.
Config Replacer: Target config length: 50412.
Config Replacer: Getting current config db.
Config Replacer: Generating patch between target config and current config db.
Config Replacer: Applying patch using 'Patch Applier'.
Patch Applier: localhost: Patch application starting.
Patch Applier: localhost: Patch: [{"op": "remove", "path": "/INTERFACE/EthernetJustMadeUp"}, {"op": "remove", "path": "/INTERFACE/Ethernet-totally-not-real"}, {"op": "remove", "path": "/INTERFACE/EthernetNR"}, {"op": "remove", "path": "/INTERFACE/Ethernet99999999"}, {"op": "remove", "path": "/INTERFACE/EthernetJustMadeUp|1.2.3.4~132"}, {"op": "remove", "path": "/INTERFACE/Ethernet99999999|1.2.3.4~132"}, {"op": "remove", "path": "/INTERFACE/Ethernet-totally-not-real|1.2.3.4~132"}, {"op": "remove", "path": "/INTERFACE/EthernetNR|1.2.3.4~132"}]
Patch Applier: localhost getting current config db.
Patch Applier: localhost: simulating the target full config after applying the patch.
Patch Applier: localhost: validating all JsonPatch operations are permitted on the specified fields
Patch Applier: localhost: validating target config does not have empty tables,
                            since they do not show up in ConfigDb.
Patch Applier: localhost: sorting patch updates.
Failed to replace config
Usage: config replace [OPTIONS] TARGET_FILE_PATH
Try "config replace -h" for help.

Error: Data Loading Failed
Leafref "/sonic-port:sonic-port/sonic-port:PORT/sonic-port:PORT_LIST/sonic-port:name" of value "EthernetNR" points to a non-existing leaf.
New command output (if the output of a command-line utility has changed)
admin@gold113-dut:~$ sudo config interface ip add EthernetNR.10 1.2.3.4
Usage: config interface ip add [OPTIONS] <interface_name> <ip_addr> <default
                               gateway IP address>
Try "config interface ip add -h" for help.

Error: Interface EthernetNR.10 does not exist