Exclude Smart Switch from modular chassis operations/checks (#3988)
Why I did it
When running the test_fwutil_update_current test in https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/fwutil/test_fwutil.py we encounter the following issue when we run the command

admin@sonic:$ sudo fwutil update chassis component ONIE fw -y

Error: Failed to parse "platform_components.json": invalid platform schema: "module" key hasn't been found. Aborting...

Aborted!
This is because platform_components.json for smartswitch doesn't have module key in it and this should be ignored for smartswitch.

What I did
Avoid any modular chassis operations on smart-switch.

How I did it
Added a check to verify the device is not a smart switch before treating it as a modular chassis.